name: Build and publish Docker Images

# For more details on events that trigger workflows see:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      - "images/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "images/**"
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dockerfiles.outputs.tags }}
    steps:
      - id: dockerfiles
        run: |
          echo "::set-output name=tags::$(find images/ -name 'Dockerfile.*' -print | jq -nR '[inputs | split(".")[-1]]')"

  build-push:
    name: Build and publish Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: ${{fromJson(needs.setup.outputs.matrix)}}

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: images/
          file: images/Dockerfile.${{matrix.tag}}
          tags: |
            rpersee/coder-workspace:${{matrix.tag}}
          push: true